In [2]:
import pandas as pd

In [1]:
#Halp

In [1]:
1+1

2

In [3]:
a=2*3

In [4]:
print(a)

6


#Hello

*hi is this big?

"Ma

# Ma Ma I'm Sorry Ma


* Dot Point!

**Feelin Bold**

**_Wombo_**

In [5]:
import numpy as np

In [6]:
arr1=np.array[1,1,1,1,1]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [7]:
arr1=np.array([8,7,6,5,4,3,2])

In [8]:
print(arr1)

[8 7 6 5 4 3 2]


In [12]:
arr2=np.array([[1,1,1],[1,2,3],[4,4,4]])
print(arr2)

[[1 1 1]
 [1 2 3]
 [4 4 4]]


In [14]:
#An array with two rows and 3 coloumns
arr4=np.zeros((2,3))
print(arr4)


[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [16]:
#Same principle but with ones
arr5=np.ones((5,2))
print(arr5)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [18]:
#Generating an array with the intergers from 0 to 10
seq1=np.arange(10)
print(seq1)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
#Generateing 21 equally spaced points between 30 and 40
seq2=np.linspace(30,40,21)
print(seq2)

[ 30.   30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5
  36.   36.5  37.   37.5  38.   38.5  39.   39.5  40. ]


In [23]:
earr=np.array([[1,1,1],[2,2,2],[3,3,3]])
print(earr)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [30]:
#Taking out the 2nd element in the array (remember the 2nd element is given by 2-1)
earr[1]

array([2, 2, 2])

In [27]:
#Selecting elements past a certain point
earr[1:]

array([[2, 2, 2],
       [3, 3, 3]])

In [32]:
#Selecting Elements between certain points
earr[1:2]

array([[2, 2, 2]])

In [35]:
#A for loop just showing how it works and how indentation is applied
for i in range(0,10):
    h=(i*3)+7
    print(h)
    print('loop is still going')
print('loop is over')

7
loop is still going
10
loop is still going
13
loop is still going
16
loop is still going
19
loop is still going
22
loop is still going
25
loop is still going
28
loop is still going
31
loop is still going
34
loop is still going
loop is over


In [36]:
#Getting a foor loop to print out specific logic
starlist=['Betelgeuse','Sirius','Canopus','Aldebaran']
for star in starlist:
    print(star,'is bright')

Betelgeuse is bright
Sirius is bright
Canopus is bright
Aldebaran is bright
